### ISSUE TITLE
Mario Leaving a Trail

### ISSUE THREAD

**Issue by robgraves** [danshadeck/spg1#2]
(I'm gonna try to use this like it's intended) So we have mario movable now on at least the 1st floor, we need to add movement up/down when in the ladder regions.  But an existing bug we currently have and don't necessarily have a resolution to yet is the trail that mario leaves behind.

**Comment by wedge1020** [comment]
Trailing occurs when (typically) one of two things happens:

1) If you are doing the paint and clear method (putting mario on the screen, rest of game loop, then putting a blank space over where mario was before putting mario on the screen in a potentially new position), make sure that:
    - The blanking sprite is the same size (at least) as the mario sprite
    - The blanking sprite is put in the SAME PLACE as the painted mario sprite you wish to get rid of (and NOT in the NEW location).  <-- this tends to be the usual culprit

2) If you are just doing a full screen redraw, with all assets each game loop, make sure you're actually painting on a new background each time, and not merely repainting on an already painted background. And by background, even if solid black, you'd need to paint on a solid black image (Also of correct size... if it is too small, you may encounter weird trailing but only in certain parts of the screen (i.e. once you've gone off the image)).

**Comment by robgraves** [comment]
OMG! wedge actually DOES use his github account.  We'll have to pursue some of these options on Tuesday.  I personally have been forbidden from attempting to solve any more problems in this game before Tuesday.

**Comment by danshadeck** [comment]
@robgraves, we can totally do this after Joe's class (or during) if you want! I just didn't want to leave Zack out of the loop/have to much to show him.

**Comment by robgraves** [comment]
yeah I understand, you just leave me chomping at the bit all the time cause I have no social life, or social skills, or any life really... :(  ...which just leaves me itching to at least TRY to fix things if I can, although not necessarily that I'm even capable of it, but maybe...just maybe...

**Comment by wedge1020** [comment]
I get an e-mail overtime a thing gets posted... so if using the more social networking aspects of GitHub counts as "using my account", so be it... still haven't touched the git repo :)

And: there's always the NES simulator, I'd love to toss e-mails and messages back and forth. Once you see its magic, there'll be tons to play with.

**Comment by robgraves** [comment]
I still feel like I have a "deer in headlights" feeling with the NES emulator.  Part of it might be like I don't know if we're reinventing the wheel everytime for each script, like the one we mentioned in class was the add.sh, all that would need to be changed was the + sign to a - to make the functional subtract script, is copying that existing functional add and modifying it to subtract (one character change) an acceptable way to do it or do you want us to write out each thing from scratch?  I guess if ultimately all that matters is the end goal of getting all to work and get each cog built regardless of how.  My internal conflict is my idea that is is stil ultimately "school" and my idea of school is that I have to produce something original for everything, or is that a wrong approach int his type of endeavor?

**Comment by wedge1020** [comment]
justgolden07: FYI, this is an off-topic comment related to another class I have with Matt and Dan; so not to worry!

We're largely re-inventing the wheel-- there will be a LOT of redundancy (doing mostly the exact same thing, save for some minor change)... your example of add vs. subtract is a perfect one.

And it isn't just you... most in the class don't yet see the glory of what we're pursuing yet, as you're either trying to focus on a very unclear final picture (very big, very many parts, how does it all fit together?) or trying to see how one little piece (like add) fits into the whole picture. We necessarily need to trudge forward without a clear picture (as Gandalf says in the Hobbit to the dwarves "do NOT stray from the path"), but eventually it will become clearer and clearer (with the occasional moment of strong clarity).

The NES simulator, being THE project for HPC Systems & Networking, allows us an opportunity to indulge in an increasingly rare opportunity on one's educational journey- to strengthen one's grasp on existing material (shell scripting, problem solving, tool creating/using). Often times "school" only presents you an initial learning opportunity, of a thing (in isolation) then after a semester leaves it alone, never to really be looked at again. Here we are intentionally revisiting all of that... for the purpose of learning some new skills (however indirectly)... but it is an opportunity to solve problems using the skills you already know how, in a slowly escalating domain building up to that final destination (a working NES simulator).

Don't look at it as an NES simulator, there are too many details to worry about at this point. Look at it as a higher-level utility suite... library actions, logic, data manipulation. All very familiar things by themselves, but strung along by some "crazy rantings" by me.

What will be original here will be the end result.. nobody else (to my knowledge) has ever produced an NES simulator out of a mish-mash of shell scripts, C programs, and a general hyper-modular design (and where there is no expectation of interactive, playable performance). As such, I think "simulator" is a far more accurate word than "emulator" here... we're not after reproducing exact functionality... instead we want (ultimately) something that will let us pick apart and study various aspects of the NES in action (how things work the way they do, how game logic flows).

There will be a lot of redundancy and near-copying of a lot of code, especially in this first phase. We're sort of tending to two layers at once (the low-level functionality-- the logic operations and number format conversions, etc., and the end-result CPU instructions built upon them), and it is going to take us reaching critical mass before connections of understanding really start firing off.

This "conflict" or "uncertainty" is also common and even expected.. as we're peeling away the materialistic learning of small skills (if statements, logic, loops) and instead focusing on some more abstract problem (how all of this will eventually start working together to do something grander than the sum of its parts). In some ways this is a taste of what one would find in a capstone course or the upper level courses of a Bachelor's degree or even Master's degree program-- where these small details aren't what important, but are still needed to accomplish the much bigger less clear thing (only, in contrast to those, you're not expected to do it by yourself and ensure all the code is yours and original, so it will hopefully be both easier and far more valuable due to our intentionally collaborative focus).

And we have an exceptional group of people in the class (a great range of skills and experiences, all able to offer unique and valuable contributions to both the project at hand and our individual educational benefit from working together)... but all facing similar reservations or uncertainties. We've been taking it slow, repeating some things, and in time amazing things will start happening. For instance, this week I'm thinking we'll continue by picking some random instruction and just working through it (what sub-steps go into making it do its thing, what things will it change to other parts of the CPU, maybe identify some new scripts/programs that need to be written).

And don't worry about making mistakes! That's what version control is for. When working on something, do it the way you think it should be... ask questions, but don't not start if you aren't sure if it is exactly what I want... for even if it isn't, that's just a future revision (and even if it is, we may find a need to change it down the road as we bring new functionality on-line).

**Comment by robgraves** [comment]
Resolved...closing issue...
